#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# This case uses the disposable app started separately in terminal A.
# No credentials or OAuth callback URLs are captured by this script.
CASE_ROOT="$(cd -- "$(dirname -- "$0")/.." && pwd)"
cd -- "$CASE_ROOT"

case_codex() {
  codex -c 'mcp_servers.skyttel_development_case.url="http://localhost:3301/mcp"' "$@"
}

cleanup_hint() {
  note "For interrupted runs: revoke the test connection in Skyttel."
  note "Run the dedicated mcp logout command in docs/development/assistants.md."
  note "Then close the private browser window and stop terminal A with Ctrl+C."
}

trap cleanup_hint EXIT
[[ -t 0 && -t 1 ]] || { printf 'Run this wizard in an interactive terminal.\n' >&2; exit 1; }
command -v codex >/dev/null || { printf 'Codex CLI is required.\n' >&2; exit 1; }
command -v curl >/dev/null || { printf 'curl is required.\n' >&2; exit 1; }

banner "AI-07: local Codex and Google"

stage "Check the disposable installation"
say "Read docs/manual-tests/assistants.md, case AI-07, before continuing."
say "Terminal A must run the isolated setup from docs/development/assistants.md."
say "Keep this terminal B open. Use a NEW private host-browser window."
say "VS Code must forward port 3301 to host port 3301."
curl --fail --silent --show-error http://localhost:3301/healthz
printf '\n'
codex --version
step "Open http://localhost:3301 in the private window and sign in with Google."
step "Check that this is TestHousehold with the fictional demo data and your unsaved draft."
confirm "Is terminal A using a NEW temporary database for this run?" || exit 1

stage "Give the first consent"
say "The CLI below prints the authorization URL. Open it in your private browser."
step "Check your user and client, select TestHousehold, and read the AI notice."
step "Select the separate AI choice, then Godkänn läsåtkomst."
step "Paste the complete final callback URL ONLY into the waiting CLI prompt."
note "A browser connection error at that callback can be expected."
note "Do not paste the callback into a chat or an evidence report."
case_codex mcp login skyttel_development_case --no-browser \
  --oauth-client-registration dcr --scopes skyttel:read

stage "Read, revoke, and check the still-open client"
say "Use only MCP server skyttel_development_case; never local files or shell reads."
step "Ask read_map for Familjens Molnmusik: 149 kr/month, Alex, Kim and Familjens musikkort."
step "Ask read_map for Familjens musikkonto, then read_my_draft without arguments."
step "Check saved familjen@example.test versus draft musik@example.test."
step "Inspect real MCP calls and results, not just the model's answer."
step "KEEP Codex open. In Skyttel, open Assistentanslutningar and revoke this client."
step "Ask for a NEW read_map call. Do not grant consent again yet."
step "Confirm it returns no new map data. Conversation history is not a fresh read."
step "Exit Codex only after checking the denied call."
pause "Press Enter to start the interactive client."
case_codex

stage "Reconnect with new consent"
case_codex mcp logout skyttel_development_case
say "Repeat Google/Skyttel consent with the URL printed below."
say "Google may remember you; a NEW Skyttel consent is still required."
case_codex mcp login skyttel_development_case --no-browser \
  --oauth-client-registration dcr --scopes skyttel:read
step "Ask for a NEW read_map for Familjens Molnmusik and inspect success."
step "Revoke this new connection in Skyttel, then exit Codex."
pause "Press Enter to start the reconnected client."
case_codex

stage "Clean up and record the result"
step "Ensure the final test connection is revoked in Assistentanslutningar."
confirm "Have you revoked the final test connection?" || exit 1
case_codex mcp logout skyttel_development_case
step "Close the private browser window."
step "Press Ctrl+C in terminal A; verify its temporary directory is removed."
step "Record AI-07's date, commit, client/browser, observed results and cleanup in issue #97."
step "Use passed, failed, blocked or not run for each check; omit secrets and callback queries."
note "This wizard does not decide or record a test result."
pause "Press Enter after cleanup and recording the result."
trap - EXIT
finish
say "The manual workflow is finished. Its outcome is the result you recorded in #97."

